[package]
name = "percy"
version = "0.1.0"
authors = ["Rahul D. Ghosal <rdghosal@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "percy"

[dependencies]
