classDiagram
    class `pydantic.BaseModel`
    `pydantic.BaseModel` <|-- MyFirstModel
    class MyFirstModel{
        +id pydantic.StrictInt
        +name str
    }
    `pydantic.BaseModel` <|-- MySecondModel
    class MySecondModel{
        +id pydantic.StrictInt
        +name str
        +key(self) str
    }
    MySecondModel <|-- MyThirdModel
    class MyThirdModel{
        +id pydantic.StrictInt
        +name str
    }