classDiagram
    class `pydantic.BaseModel`
    `pydantic.BaseModel` <|-- MyFirstModel
    class MyFirstModel{
        +id pydantic.StrictInt
        +name str
        +get_random_list(self) list[int | float]
    }
    `pydantic.BaseModel` <|-- MySecondModel
    class MySecondModel{
        +id pydantic.StrictInt
        +name str
        +key(self) str
    }
    MySecondModel <|-- MyThirdModel
    class MyThirdModel{
        +id pydantic.StrictInt
        +name str
        -_increase_id(self) None
    }